export const ABONNEMENT_LIST_REQUEST = "ABONNEMENT_LIST_REQUEST";
export const ABONNEMENT_LIST_SUCCESS = "ABONNEMENT_LIST_SUCCESS";
export const ABONNEMENT_LIST_FAIL = "ABONNEMENT_LIST_FAIL";

export const ABONNEMENT_DETAILS_REQUEST = "ABONNEMENT_DETAILS_REQUEST";
export const ABONNEMENT_DETAILS_SUCCESS = "ABONNEMENT_DETAILS_SUCCESS";
export const ABONNEMENT_DETAILS_FAIL = "ABONNEMENT_DETAILS_FAIL";

export const ABONNEMENT_DELETE_REQUEST = "ABONNEMENT_DELETE_REQUEST";
export const ABONNEMENT_DELETE_SUCCESS = "ABONNEMENT_DELETE_SUCCESS";
export const ABONNEMENT_DELETE_FAIL = "ABONNEMENT_DELETE_FAIL";

export const ABONNEMENT_CREATE_REQUEST = "ABONNEMENT_CREATE_REQUEST";
export const ABONNEMENT_CREATE_SUCCESS = "ABONNEMENT_CREATE_SUCCESS";
export const ABONNEMENT_CREATE_FAIL = "ABONNEMENT_CREATE_FAIL";
export const ABONNEMENT_CREATE_RESET = "ABONNEMENT_CREATE_RESET";

export const ABONNEMENT_UPDATE_REQUEST = "ABONNEMENT_UPDATE_REQUEST";
export const ABONNEMENT_UPDATE_SUCCESS = "ABONNEMENT_UPDATE_SUCCESS";
export const ABONNEMENT_UPDATE_FAIL = "ABONNEMENT_UPDATE_FAIL";
export const ABONNEMENT_UPDATE_RESET = "ABONNEMENT_UPDATE_RESET";

export const ABONNEMENT_CREATE_REVIEW_REQUEST =
  "ABONNEMENT_CREATE_REVIEW_REQUEST";
export const ABONNEMENT_CREATE_REVIEW_SUCCESS =
  "ABONNEMENT_CREATE_REVIEW_SUCCESS";
export const ABONNEMENT_CREATE_REVIEW_FAIL = "ABONNEMENT_CREATE_REVIEW_FAIL";
export const ABONNEMENT_CREATE_REVIEW_RESET = "ABONNEMENT_CREATE_REVIEW_RESET";

export const ABONNEMENT_TOP_REQUEST = "ABONNEMENT_TOP_REQUEST";
export const ABONNEMENT_TOP_SUCCESS = "ABONNEMENT_TOP_SUCCESS";
export const ABONNEMENT_TOP_FAIL = "ABONNEMENT_TOP_FAIL";
